//! Build script: auto-generates `src/scenarios/mod.rs` by scanning
//! `src/scenarios/*.rs` files, extracting their `pub struct` names,
//! and emitting `mod` declarations + `all_scenarios()` registration.
//!
//! Drop a new `.rs` file in `src/scenarios/` and it's auto-discovered
//! on the next build — no manual `mod.rs` maintenance required.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

fn main() {
    let scenarios_dir = Path::new("src/scenarios");

    // Tell Cargo to re-run if any file in the scenarios directory changes.
    println!("cargo::rerun-if-changed=src/scenarios");

    let mut modules: Vec<ModuleInfo> = Vec::new();

    let entries = match fs::read_dir(scenarios_dir) {
        Ok(e) => e,
        Err(e) => {
            eprintln!("warning: cannot read scenarios dir: {}", e);
            return;
        }
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let file_name = entry.file_name().to_string_lossy().to_string();

        // Skip non-.rs files, mod.rs itself, and files with non-module-safe names
        // (e.g., dual_cluster_mDNS_isolation.rs has capital letters — not a valid Rust module)
        if !file_name.ends_with(".rs") || file_name == "mod.rs" {
            continue;
        }

        let mod_name = file_name.trim_end_matches(".rs").to_string();

        // Skip files with uppercase letters — not valid Rust module names
        if mod_name.chars().any(|c| c.is_uppercase()) {
            continue;
        }

        let content = match fs::read_to_string(&path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        // Extract the pub struct name (must be at line start: `pub struct FooBar;`)
        let struct_name = content
            .lines()
            .find_map(|line| {
                let trimmed = line.trim();
                if trimmed.starts_with("pub struct ") {
                    let rest = &trimmed["pub struct ".len()..];
                    let name = rest
                        .split(|c: char| !c.is_alphanumeric() && c != '_')
                        .next()
                        .unwrap_or("");
                    if !name.is_empty() {
                        Some(name.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                }
            });

        // Extract the ADR tag from fn adr() return value
        let adr = content
            .lines()
            .find_map(|line| {
                let trimmed = line.trim();
                if trimmed.contains("ADR-") && (trimmed.contains("fn adr") || trimmed.contains('"')) {
                    // Match patterns like: "ADR-001" or ADR-001
                    let start = trimmed.find("ADR-")?;
                    let rest = &trimmed[start..];
                    let end = rest.find('"').unwrap_or(rest.len());
                    let adr_str = &rest[..end];
                    // Validate it's a real ADR reference (ADR-NNN)
                    if adr_str.len() >= 7 && adr_str[4..].chars().all(|c| c.is_ascii_digit()) {
                        Some(adr_str.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                }
            });

        if let Some(struct_name) = struct_name {
            modules.push(ModuleInfo {
                mod_name,
                struct_name,
                adr: adr.unwrap_or_else(|| "ADR-???".to_string()),
            });
        }
    }

    // Sort by ADR number then module name for stable output
    modules.sort_by(|a, b| {
        let a_num = adr_sort_key(&a.adr);
        let b_num = adr_sort_key(&b.adr);
        a_num.cmp(&b_num).then(a.mod_name.cmp(&b.mod_name))
    });

    // Group by ADR for commented sections
    let mut by_adr: BTreeMap<String, Vec<&ModuleInfo>> = BTreeMap::new();
    for m in &modules {
        by_adr.entry(m.adr.clone()).or_default().push(m);
    }

    // Generate mod.rs content
    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs — do not edit manually.\n");
    output.push_str("// Drop a .rs file in src/scenarios/ and it will be discovered on next build.\n\n");

    // Module declarations grouped by ADR
    for (adr, mods) in &by_adr {
        output.push_str(&format!("// {}\n", adr));
        for m in mods {
            output.push_str(&format!("mod {};\n", m.mod_name));
        }
    }

    output.push('\n');
    output.push_str("use crate::harness::runner::Scenario;\n\n");
    output.push_str("/// Return all registered scenarios (auto-discovered from src/scenarios/*.rs).\n");
    output.push_str("pub fn all_scenarios() -> Vec<Box<dyn Scenario>> {\n");
    output.push_str("    vec![\n");

    for (adr, mods) in &by_adr {
        output.push_str(&format!("        // {}\n", adr));
        for m in mods {
            output.push_str(&format!(
                "        Box::new({}::{}),\n",
                m.mod_name, m.struct_name
            ));
        }
    }

    output.push_str("    ]\n");
    output.push_str("}\n");

    // Write the generated mod.rs
    let mod_path = scenarios_dir.join("mod.rs");
    let existing = fs::read_to_string(&mod_path).unwrap_or_default();

    // Only write if content changed (avoids unnecessary rebuilds)
    if existing != output {
        fs::write(&mod_path, &output).expect("failed to write scenarios/mod.rs");
    }
}

struct ModuleInfo {
    mod_name: String,
    struct_name: String,
    adr: String,
}

fn adr_sort_key(adr: &str) -> u32 {
    adr.strip_prefix("ADR-")
        .and_then(|s| s.parse::<u32>().ok())
        .unwrap_or(999)
}
