[package]
name        = "picloud-network"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
picloud-domain = { workspace = true }
tokio          = { workspace = true }
async-trait    = { workspace = true }
tracing        = { workspace = true }
thiserror      = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
rustls         = { workspace = true }
rustls-pemfile = { workspace = true }
rcgen          = { workspace = true }
webpki-roots = { workspace = true }
x509-parser  = { workspace = true }
mdns-sd      = { workspace = true }
uuid         = { workspace = true }
chrono       = { workspace = true }
sha2         = { workspace = true }
ring         = { workspace = true }
rand          = { workspace = true }
hickory-proto = { workspace = true }
