[package]
name        = "picloud-http"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
picloud-domain = { workspace = true }
tokio          = { workspace = true }
async-trait    = { workspace = true }
tracing        = { workspace = true }
thiserror      = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
axum       = { workspace = true }
tower      = { workspace = true }
tower-http = { workspace = true }
hyper      = { workspace = true }
reqwest        = { workspace = true }
uuid           = { workspace = true }
futures        = { workspace = true }
rustls         = { workspace = true }
tokio-rustls   = { workspace = true }
rustls-pemfile = { workspace = true }
axum-server    = { workspace = true }
async-stream = "0.3"

[dev-dependencies]
http             = "1"
picloud-events   = { workspace = true }
picloud-rdf      = { workspace = true }
async-trait      = { workspace = true }
