// Auto-generated by build.rs — do not edit manually.
// Drop a .rs file in src/scenarios/ and it will be discovered on next build.

// ADR-001
mod binary_compiles;
mod no_runtime_panics;
// ADR-002
mod multi_node_failover;
mod raft_leader_election;
mod raft_leader_failover;
mod raft_learner_join;
// ADR-003
mod dns_resolution;
mod node_join_dns;
mod product_fqdn_dns;
// ADR-004
mod event_log_replay;
mod event_ordering;
mod multi_node_persistence;
mod projection_consistency;
// ADR-005
mod graph_isolation;
mod rdf_projection_roundtrip;
mod sparql_query_types;
// ADR-006
mod named_graph_isolation;
mod oxigraph_persistence;
mod oxigraph_sparql_compliance;
// ADR-007
mod invalid_syntax_rejection;
mod picloud_syntax_parse;
mod symbolic_reference_resolution;
// ADR-008
mod command_correlation;
mod concurrent_commands;
mod progress_streaming;
// ADR-009
mod human_identity_lifecycle;
mod token_expiry_enforcement;
// ADR-010
mod binary_workload;
mod container_schedule;
mod workload_identity_injection;
// ADR-011
mod phase_dependency_order;
mod product_sparql;
mod replication_coverage;
mod volume_mount;
// ADR-012
mod mounted_volume;
mod raw_block_device;
mod volume_mount_restart;
// ADR-013
mod full_replication_coverage;
mod multi_node_replication;
mod replication_on_node_join;
// ADR-014
mod cross_product_isolation;
mod internal_dns_resolution;
// ADR-015
mod idempotency_key_uniqueness;
mod idempotent_apply;
mod partial_failure_reapply;
// ADR-016
mod cascading_delete;
mod orphan_prevention;
mod product_full_lifecycle;
// ADR-017
mod jwks_key_rotation;
mod oidc_authorization_code;
mod oidc_client_credentials;
// ADR-018
mod direct_network_blocked;
mod event_bus_burst;
mod inter_product_event_delivery;
// ADR-019
mod ontology_served;
mod product_sparql_endpoint;
mod sparql_iam_enforcement;
// ADR-020
mod cluster_registry_discovery;
mod registry_version_binding;
// ADR-021
mod atomic_version_cutover;
mod failed_upgrade_rollback;
mod one_active_version_invariant;
// ADR-022
mod event_subscription_provisioning;
mod subscription_lifecycle;
mod undeclared_subscription_rejection;
// ADR-023
mod ontology_shacl_validation;
mod ontology_version_binding;
// ADR-024
mod intent_translated_to_implementation;
mod storage_intent_full_replication;
// ADR-025
mod fido2_cli_auth;
mod passkey_registration;
mod webauthn_challenge_replay_rejection;
// ADR-026
mod bootstrap_token_expiry;
mod bootstrap_token_single_use;
mod tier1_admin_reset;
mod tier3_physical_recovery;
// ADR-027
mod mtls_enforcement;
mod sparql_direct_mtls;
mod workload_cert_injection;
// ADR-028
mod no_cross_slice_imports;
mod slice_dependency_enforcement;
// ADR-029
mod content_negotiation;
mod iri_dereferencing;
mod iri_stability;
// ADR-030
mod byo_ca;
mod cert_chain_validation;
mod platform_ca_export;
// ADR-031
mod schema_evolution;
mod schema_iri_permanence;
mod schema_iri_resolution;
// ADR-032
mod event_store_append_read;
mod event_store_rdf_projection;
mod event_store_replay;
mod event_store_survivor;
// ADR-033
mod sdk_generation;
mod sdk_ontology_sync;
mod sdk_publish;
// ADR-034
mod composition_root_only;
mod per_slice_build;
// ADR-035
mod aggregate_replay;
mod platform_replay_full;
mod replay_marked_flag;
mod shadow_swap_live_traffic;
// ADR-036
mod tag_add_event;
mod tag_rdf_projection;
mod tag_remove;
mod tag_sparql_queryable;
// ADR-037
mod circular_group_rejection;
mod group_membership_removal;
mod group_membership_via_inference;
mod group_role_inheritance;
// ADR-038
mod inference_retraction;
mod inference_rule_lifecycle;
mod reconciliation_pass;
mod rule_idempotency;
// ADR-039
mod ontology_deploy_immediate;
mod owl_transitivity;
mod rdfs_subclass_inference;
// ADR-040
mod metrics_collection_interval;
mod metrics_rdf_projection;
mod metrics_upsert;
// ADR-041
mod alert_dampening;
mod alert_fired;
mod alert_resolved;
mod all_builtin_rules;
// ADR-042
mod cross_cluster_join_rejection;
mod dual_cluster_mdns_isolation;
mod iri_namespace_uniqueness;
// ADR-043
mod config_api_lifecycle;
mod config_live_reload;
mod config_secret_separation;
mod workload_config_override;
// ADR-044
mod flag_in_process_evaluation;
mod flag_live_update;
mod flag_version_evaluation;
mod flag_version_range;
mod new_resource_flags;
// ADR-045
mod cli_trace_propagation;
mod otel_does_not_starve_raft;
mod otlp_trace_ingestion;
// ADR-046
mod datafusion_time_range;
mod parquet_portability;
mod parquet_write_read;
mod retention_enforcement;
// ADR-047
mod backup_failure_alert;
mod offsite_backup_complete;
mod snapshot_create_verify;
mod snapshot_restore;
mod snapshot_retention;
// ADR-048
mod ingress_host_routing;
mod internal_port_isolation;
mod sni_cert_selection;
mod workload_reschedule_routing;
// ADR-049
mod compiler_roundtrip;
mod iri_determinism;
mod offline_validation;
mod shacl_validation_errors;
// ADR-050
mod auto_validation_failure;
mod new_resource_partial;
mod overwrite_protection;
// ADR-051
mod audience_enforcement;
mod m2m_permission_required;
mod role_inheritance_claims;
mod token_exchange_on_behalf_of;
// ADR-052
mod dns_a_records;
mod dns_cache_invalidation;
mod dns_nxdomain;
mod dns_srv_records;
mod dns_txt_records;
// ADR-053
mod auto_enroll_mode;
mod cert_revocation;
mod csr_wildcard_rejection;
mod token_enroll_expiry;
mod token_enroll_single_use;
// ADR-054
mod adr_test_coverage_completeness;
mod scenario_catalogue_sync;
// ADR-055
mod rolling_upgrade_sequence;
mod upgrade_compatibility;
mod upgrade_gate_enforcement;
// ADR-056
mod port_non_conflict;
mod shared_hardware_isolation;
// ADR-057
mod version_attribute_present;
mod version_matches_cluster;
// ADR-058
mod no_internal_imports;
mod test_crate_builds_independently;

use crate::harness::runner::Scenario;

/// Return all registered scenarios (auto-discovered from src/scenarios/*.rs).
pub fn all_scenarios() -> Vec<Box<dyn Scenario>> {
    vec![
        // ADR-001
        Box::new(binary_compiles::BinaryCompiles),
        Box::new(no_runtime_panics::NoRuntimePanics),
        // ADR-002
        Box::new(multi_node_failover::MultiNodeFailover),
        Box::new(raft_leader_election::RaftLeaderElection),
        Box::new(raft_leader_failover::RaftLeaderFailover),
        Box::new(raft_learner_join::RaftLearnerJoin),
        // ADR-003
        Box::new(dns_resolution::DnsResolutionScenario),
        Box::new(node_join_dns::NodeJoinDns),
        Box::new(product_fqdn_dns::ProductFqdnDns),
        // ADR-004
        Box::new(event_log_replay::EventLogReplay),
        Box::new(event_ordering::EventOrdering),
        Box::new(multi_node_persistence::MultiNodePersistence),
        Box::new(projection_consistency::ProjectionConsistency),
        // ADR-005
        Box::new(graph_isolation::GraphIsolation),
        Box::new(rdf_projection_roundtrip::RdfProjectionRoundtrip),
        Box::new(sparql_query_types::SparqlQueryTypes),
        // ADR-006
        Box::new(named_graph_isolation::NamedGraphIsolation),
        Box::new(oxigraph_persistence::OxigraphPersistence),
        Box::new(oxigraph_sparql_compliance::OxigraphSparqlCompliance),
        // ADR-007
        Box::new(invalid_syntax_rejection::InvalidSyntaxRejection),
        Box::new(picloud_syntax_parse::PicloudSyntaxParse),
        Box::new(symbolic_reference_resolution::SymbolicReferenceResolution),
        // ADR-008
        Box::new(command_correlation::CommandCorrelation),
        Box::new(concurrent_commands::ConcurrentCommands),
        Box::new(progress_streaming::ProgressStreaming),
        // ADR-009
        Box::new(human_identity_lifecycle::HumanIdentityLifecycleScenario),
        Box::new(token_expiry_enforcement::TokenExpiryEnforcement),
        // ADR-010
        Box::new(binary_workload::BinaryWorkloadScenario),
        Box::new(container_schedule::ContainerSchedule),
        Box::new(workload_identity_injection::WorkloadIdentityInjectionScenario),
        // ADR-011
        Box::new(phase_dependency_order::PhaseDependencyOrder),
        Box::new(product_sparql::ProductSparqlScenario),
        Box::new(replication_coverage::ReplicationCoverageScenario),
        Box::new(volume_mount::VolumeMountScenario),
        // ADR-012
        Box::new(mounted_volume::MountedVolume),
        Box::new(raw_block_device::RawBlockDevice),
        Box::new(volume_mount_restart::VolumeMountRestart),
        // ADR-013
        Box::new(full_replication_coverage::FullReplicationCoverage),
        Box::new(multi_node_replication::MultiNodeReplication),
        Box::new(replication_on_node_join::ReplicationOnNodeJoin),
        // ADR-014
        Box::new(cross_product_isolation::CrossProductIsolation),
        Box::new(internal_dns_resolution::InternalDnsResolution),
        // ADR-015
        Box::new(idempotency_key_uniqueness::IdempotencyKeyUniqueness),
        Box::new(idempotent_apply::IdempotentApply),
        Box::new(partial_failure_reapply::PartialFailureReapply),
        // ADR-016
        Box::new(cascading_delete::CascadingDelete),
        Box::new(orphan_prevention::OrphanPrevention),
        Box::new(product_full_lifecycle::ProductFullLifecycle),
        // ADR-017
        Box::new(jwks_key_rotation::JwksKeyRotation),
        Box::new(oidc_authorization_code::OidcAuthorizationCode),
        Box::new(oidc_client_credentials::OidcClientCredentials),
        // ADR-018
        Box::new(direct_network_blocked::DirectNetworkBlocked),
        Box::new(event_bus_burst::EventBusBurst),
        Box::new(inter_product_event_delivery::InterProductEventDelivery),
        // ADR-019
        Box::new(ontology_served::OntologyServed),
        Box::new(product_sparql_endpoint::ProductSparqlEndpoint),
        Box::new(sparql_iam_enforcement::SparqlIamEnforcement),
        // ADR-020
        Box::new(cluster_registry_discovery::ClusterRegistryDiscovery),
        Box::new(registry_version_binding::RegistryVersionBinding),
        // ADR-021
        Box::new(atomic_version_cutover::AtomicVersionCutoverScenario),
        Box::new(failed_upgrade_rollback::FailedUpgradeRollback),
        Box::new(one_active_version_invariant::OneActiveVersionInvariant),
        // ADR-022
        Box::new(event_subscription_provisioning::EventSubscriptionProvisioning),
        Box::new(subscription_lifecycle::SubscriptionLifecycle),
        Box::new(undeclared_subscription_rejection::UndeclaredSubscriptionRejection),
        // ADR-023
        Box::new(ontology_shacl_validation::OntologyShaclValidation),
        Box::new(ontology_version_binding::OntologyVersionBinding),
        // ADR-024
        Box::new(intent_translated_to_implementation::IntentTranslatedToImplementation),
        Box::new(storage_intent_full_replication::StorageIntentFullReplication),
        // ADR-025
        Box::new(fido2_cli_auth::Fido2CliAuthScenario),
        Box::new(passkey_registration::PasskeyRegistration),
        Box::new(webauthn_challenge_replay_rejection::WebauthnChallengeReplayRejection),
        // ADR-026
        Box::new(bootstrap_token_expiry::BootstrapTokenExpiry),
        Box::new(bootstrap_token_single_use::BootstrapTokenSingleUse),
        Box::new(tier1_admin_reset::Tier1AdminReset),
        Box::new(tier3_physical_recovery::Tier3PhysicalRecovery),
        // ADR-027
        Box::new(mtls_enforcement::MtlsEnforcement),
        Box::new(sparql_direct_mtls::SparqlDirectMtls),
        Box::new(workload_cert_injection::WorkloadCertInjectionScenario),
        // ADR-028
        Box::new(no_cross_slice_imports::NoCrossSliceImports),
        Box::new(slice_dependency_enforcement::SliceDependencyEnforcement),
        // ADR-029
        Box::new(content_negotiation::ContentNegotiation),
        Box::new(iri_dereferencing::IriDereferencing),
        Box::new(iri_stability::IriStability),
        // ADR-030
        Box::new(byo_ca::ByoCa),
        Box::new(cert_chain_validation::CertChainValidation),
        Box::new(platform_ca_export::PlatformCaExport),
        // ADR-031
        Box::new(schema_evolution::SchemaEvolution),
        Box::new(schema_iri_permanence::SchemaIriPermanence),
        Box::new(schema_iri_resolution::SchemaIriResolution),
        // ADR-032
        Box::new(event_store_append_read::EventStoreAppendRead),
        Box::new(event_store_rdf_projection::EventStoreRdfProjection),
        Box::new(event_store_replay::EventStoreReplay),
        Box::new(event_store_survivor::EventStoreSurvivor),
        // ADR-033
        Box::new(sdk_generation::SdkGeneration),
        Box::new(sdk_ontology_sync::SdkOntologySync),
        Box::new(sdk_publish::SdkPublish),
        // ADR-034
        Box::new(composition_root_only::CompositionRootOnly),
        Box::new(per_slice_build::PerSliceBuild),
        // ADR-035
        Box::new(aggregate_replay::AggregateReplay),
        Box::new(platform_replay_full::PlatformReplayFull),
        Box::new(replay_marked_flag::ReplayMarkedFlag),
        Box::new(shadow_swap_live_traffic::ShadowSwapLiveTraffic),
        // ADR-036
        Box::new(tag_add_event::TagAddEvent),
        Box::new(tag_rdf_projection::TagRdfProjection),
        Box::new(tag_remove::TagRemove),
        Box::new(tag_sparql_queryable::TagSparqlQueryable),
        // ADR-037
        Box::new(circular_group_rejection::CircularGroupRejection),
        Box::new(group_membership_removal::GroupMembershipRemoval),
        Box::new(group_membership_via_inference::GroupMembershipViaInference),
        Box::new(group_role_inheritance::GroupRoleInheritance),
        // ADR-038
        Box::new(inference_retraction::InferenceRetraction),
        Box::new(inference_rule_lifecycle::InferenceRuleLifecycle),
        Box::new(reconciliation_pass::ReconciliationPass),
        Box::new(rule_idempotency::RuleIdempotency),
        // ADR-039
        Box::new(ontology_deploy_immediate::OntologyDeployImmediate),
        Box::new(owl_transitivity::OwlTransitivity),
        Box::new(rdfs_subclass_inference::RdfsSubclassInference),
        // ADR-040
        Box::new(metrics_collection_interval::MetricsCollectionInterval),
        Box::new(metrics_rdf_projection::MetricsRdfProjection),
        Box::new(metrics_upsert::MetricsUpsert),
        // ADR-041
        Box::new(alert_dampening::AlertDampening),
        Box::new(alert_fired::AlertFired),
        Box::new(alert_resolved::AlertResolved),
        Box::new(all_builtin_rules::AllBuiltinRulesScenario),
        // ADR-042
        Box::new(cross_cluster_join_rejection::CrossClusterJoinRejectionScenario),
        Box::new(dual_cluster_mdns_isolation::DualClusterMdnsIsolation),
        Box::new(iri_namespace_uniqueness::IriNamespaceUniqueness),
        // ADR-043
        Box::new(config_api_lifecycle::ConfigApiLifecycle),
        Box::new(config_live_reload::ConfigLiveReload),
        Box::new(config_secret_separation::ConfigSecretSeparation),
        Box::new(workload_config_override::WorkloadConfigOverride),
        // ADR-044
        Box::new(flag_in_process_evaluation::FlagInProcessEvaluation),
        Box::new(flag_live_update::FlagLiveUpdate),
        Box::new(flag_version_evaluation::FlagVersionEvaluationScenario),
        Box::new(flag_version_range::FlagVersionRange),
        Box::new(new_resource_flags::NewResourceFlags),
        // ADR-045
        Box::new(cli_trace_propagation::CliTracePropagation),
        Box::new(otel_does_not_starve_raft::OtelDoesNotStarveRaft),
        Box::new(otlp_trace_ingestion::OtlpTraceIngestion),
        // ADR-046
        Box::new(datafusion_time_range::DatafusionTimeRange),
        Box::new(parquet_portability::ParquetPortability),
        Box::new(parquet_write_read::ParquetWriteRead),
        Box::new(retention_enforcement::RetentionEnforcement),
        // ADR-047
        Box::new(backup_failure_alert::BackupFailureAlert),
        Box::new(offsite_backup_complete::OffsiteBackupComplete),
        Box::new(snapshot_create_verify::SnapshotCreateVerify),
        Box::new(snapshot_restore::SnapshotRestore),
        Box::new(snapshot_retention::SnapshotRetention),
        // ADR-048
        Box::new(ingress_host_routing::IngressHostRouting),
        Box::new(internal_port_isolation::InternalPortIsolationScenario),
        Box::new(sni_cert_selection::SniCertSelection),
        Box::new(workload_reschedule_routing::WorkloadRescheduleRouting),
        // ADR-049
        Box::new(compiler_roundtrip::CompilerRoundtrip),
        Box::new(iri_determinism::IriDeterminism),
        Box::new(offline_validation::OfflineValidation),
        Box::new(shacl_validation_errors::ShaclValidationErrors),
        // ADR-050
        Box::new(auto_validation_failure::AutoValidationFailureScenario),
        Box::new(new_resource_partial::NewResourcePartialScenario),
        Box::new(overwrite_protection::OverwriteProtection),
        // ADR-051
        Box::new(audience_enforcement::AudienceEnforcement),
        Box::new(m2m_permission_required::M2mPermissionRequired),
        Box::new(role_inheritance_claims::RoleInheritanceClaims),
        Box::new(token_exchange_on_behalf_of::TokenExchangeOnBehalfOf),
        // ADR-052
        Box::new(dns_a_records::DnsARecords),
        Box::new(dns_cache_invalidation::DnsCacheInvalidationScenario),
        Box::new(dns_nxdomain::DnsNxdomain),
        Box::new(dns_srv_records::DnsSrvRecords),
        Box::new(dns_txt_records::DnsTxtRecords),
        // ADR-053
        Box::new(auto_enroll_mode::AutoEnrollMode),
        Box::new(cert_revocation::CertRevocation),
        Box::new(csr_wildcard_rejection::CsrWildcardRejection),
        Box::new(token_enroll_expiry::TokenEnrollExpiry),
        Box::new(token_enroll_single_use::TokenEnrollSingleUse),
        // ADR-054
        Box::new(adr_test_coverage_completeness::AdrTestCoverageCompleteness),
        Box::new(scenario_catalogue_sync::ScenarioCatalogueSync),
        // ADR-055
        Box::new(rolling_upgrade_sequence::RollingUpgradeSequenceScenario),
        Box::new(upgrade_compatibility::UpgradeCompatibilityScenario),
        Box::new(upgrade_gate_enforcement::UpgradeGateEnforcementScenario),
        // ADR-056
        Box::new(port_non_conflict::PortNonConflictScenario),
        Box::new(shared_hardware_isolation::SharedHardwareIsolationScenario),
        // ADR-057
        Box::new(version_attribute_present::VersionAttributePresentScenario),
        Box::new(version_matches_cluster::VersionMatchesClusterScenario),
        // ADR-058
        Box::new(no_internal_imports::NoInternalImports),
        Box::new(test_crate_builds_independently::TestCrateBuildsIndependently),
    ]
}
